import fs from 'fs';
import path from 'path';
import { Response } from 'express';
import { z } from 'zod';
import { db } from '../db/database';
import { authorizationService } from '../auth/authorizationService';
import { hashPasswordSync } from '../auth/password';
import { telemetryService } from '../auth/telemetryService';
import { AuthenticatedRequest } from '../middleware/authMiddleware';

export type Organization = { id:string; name:string; code:string; status:'ACTIVE'|'ARCHIVED'; createdAt:string };
export type ClassGroup = { id:string; organizationId:string; name:string; code:string; academicYear:string; grade?:string; status:'ACTIVE'|'ARCHIVED'; createdAt:string };
export type Enrollment = { id:string; classId:string; studentId:string; status:'ACTIVE'|'INACTIVE'; enrolledAt:string };
export type TeacherAssignment = { id:string; classId:string; teacherId:string; role:'TEACHER'|'ASSISTANT_TEACHER'; status:'ACTIVE'|'INACTIVE'; assignedAt:string };
export type GuardianLink = { id:string; guardianId:string; studentId:string; relation:string; status:'ACTIVE'|'INACTIVE'; linkedAt:string };

interface State { organizations:Organization[]; classes:ClassGroup[]; enrollments:Enrollment[]; teacherAssignments:TeacherAssignment[]; guardianLinks:GuardianLink[]; }
const statePath = path.join(process.cwd(),'data','teacher_student_management.json');
const now=()=>new Date().toISOString();
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const load=():State=>{ try { if(fs.existsSync(statePath)) return JSON.parse(fs.readFileSync(statePath,'utf8')); } catch {} return {organizations:[],classes:[],enrollments:[],teacherAssignments:[],guardianLinks:[]}; };
const state:State=load();
const persist=()=>{fs.mkdirSync(path.dirname(statePath),{recursive:true}); const tmp=`${statePath}.tmp`; fs.writeFileSync(tmp,JSON.stringify(state,null,2),'utf8'); fs.renameSync(tmp,statePath);};
const ok=(req:AuthenticatedRequest,resource:string,action:string,target?:string,context?:any)=>req.user ? authorizationService.authorize({actorUserId:req.user.userId,resource,action,targetResourceId:target,context}) : {allowed:false,reason:'UNAUTHORIZED'};
const bodySchema=z.object({organizationId:z.string().min(1),name:z.string().min(2),code:z.string().min(2),academicYear:z.string().min(4),grade:z.string().optional()});
const enrollSchema=z.object({studentIds:z.array(z.string()).min(1).max(1000),classId:z.string().min(1)});
const assignSchema=z.object({teacherId:z.string().min(1),role:z.enum(['TEACHER','ASSISTANT_TEACHER']).default('TEACHER')});
const guardianSchema=z.object({guardianId:z.string(),studentId:z.string(),relation:z.string().min(2)});
function userExists(id:string, role?:string){const u=db.findUserById(id); return !!u && (!role || u.role===role || authorizationService.getUserRoles(id).includes(role as any));}

export function handleOrgClassSummary(req:AuthenticatedRequest,res:Response){ const c=ok(req,'students','view'); if(!c.allowed)return res.status(403).json({success:false,error:c.reason}); return res.json({success:true,organizations:state.organizations,classes:state.classes,enrollments:state.enrollments.length,teacherAssignments:state.teacherAssignments.length,guardianLinks:state.guardianLinks.length}); }
export function handleCreateOrganization(req:AuthenticatedRequest,res:Response){const c=ok(req,'students','create');if(!c.allowed)return res.status(403).json({success:false,error:c.reason}); const p=z.object({name:z.string().min(2),code:z.string().min(2)}).safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_ORGANIZATION'});if(state.organizations.some(x=>x.code===p.data.code))return res.status(409).json({success:false,error:'ORGANIZATION_CODE_EXISTS'});const o={id:id('org'),...p.data,status:'ACTIVE' as const,createdAt:now()};state.organizations.push(o);persist();return res.status(201).json({success:true,organization:o});}
export function handleCreateClass(req:AuthenticatedRequest,res:Response){const c=ok(req,'students','create');if(!c.allowed)return res.status(403).json({success:false,error:c.reason});const p=bodySchema.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_CLASS'});if(!state.organizations.some(x=>x.id===p.data.organizationId&&x.status==='ACTIVE'))return res.status(404).json({success:false,error:'ORGANIZATION_NOT_FOUND'});if(state.classes.some(x=>x.organizationId===p.data.organizationId&&x.code===p.data.code))return res.status(409).json({success:false,error:'CLASS_CODE_EXISTS'});const cl={id:id('class'),...p.data,status:'ACTIVE' as const,createdAt:now()};state.classes.push(cl);persist();return res.status(201).json({success:true,classGroup:cl});}
export function handleEnrollStudents(req:AuthenticatedRequest,res:Response){const p=enrollSchema.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_ENROLLMENT'});const c=ok(req,'students','update',p.data.classId);if(!c.allowed)return res.status(403).json({success:false,error:c.reason});if(!state.classes.some(x=>x.id===p.data.classId))return res.status(404).json({success:false,error:'CLASS_NOT_FOUND'});const result=p.data.studentIds.map(studentId=>{if(!userExists(studentId,'STUDENT'))return {studentId,success:false,error:'STUDENT_NOT_FOUND'};const exists=state.enrollments.find(x=>x.classId===p.data.classId&&x.studentId===studentId&&x.status==='ACTIVE');if(exists)return {studentId,success:true,existing:true};state.enrollments.push({id:id('enr'),classId:p.data.classId,studentId,status:'ACTIVE',enrolledAt:now()});return {studentId,success:true};});persist();telemetryService.logAudit({actorUserId:req.user!.userId,action:'STUDENT_ENROLLMENT_BULK',resourceType:'Class',resourceId:p.data.classId,result:'SUCCESS',metadata:{result}});return res.json({success:true,result});}
export function handleAssignTeacher(req:AuthenticatedRequest,res:Response){const classId=req.params.classId;const p=assignSchema.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_TEACHER_ASSIGNMENT'});const c=ok(req,'students','update',classId);if(!c.allowed)return res.status(403).json({success:false,error:c.reason});if(!state.classes.some(x=>x.id===classId))return res.status(404).json({success:false,error:'CLASS_NOT_FOUND'});if(!userExists(p.data.teacherId,p.data.role==='TEACHER'?'TEACHER':'ASSISTANT_TEACHER'))return res.status(404).json({success:false,error:'TEACHER_NOT_FOUND'});const exists=state.teacherAssignments.find(x=>x.classId===classId&&x.teacherId===p.data.teacherId&&x.status==='ACTIVE');if(exists)return res.json({success:true,assignment:exists,existing:true});const a={id:id('ta'),classId,teacherId:p.data.teacherId,role:p.data.role,status:'ACTIVE' as const,assignedAt:now()};state.teacherAssignments.push(a);persist();return res.status(201).json({success:true,assignment:a});}
export function handleGuardianLink(req:AuthenticatedRequest,res:Response){const p=guardianSchema.safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_GUARDIAN_LINK'});const c=ok(req,'students','update',p.data.studentId);if(!c.allowed)return res.status(403).json({success:false,error:c.reason});if(!userExists(p.data.guardianId,'GUARDIAN')||!userExists(p.data.studentId,'STUDENT'))return res.status(404).json({success:false,error:'USER_NOT_FOUND'});const exists=state.guardianLinks.find(x=>x.guardianId===p.data.guardianId&&x.studentId===p.data.studentId&&x.status==='ACTIVE');if(exists)return res.json({success:true,link:exists,existing:true});const link={id:id('gl'),...p.data,status:'ACTIVE' as const,linkedAt:now()};state.guardianLinks.push(link);persist();return res.status(201).json({success:true,link});}
export function handleClassRoster(req:AuthenticatedRequest,res:Response){const classId=req.params.classId;const c=ok(req,'students','view',classId);if(!c.allowed)return res.status(403).json({success:false,error:c.reason});const cls=state.classes.find(x=>x.id===classId);if(!cls)return res.status(404).json({success:false,error:'CLASS_NOT_FOUND'});const studentIds=state.enrollments.filter(x=>x.classId===classId&&x.status==='ACTIVE').map(x=>x.studentId);const teacherIds=state.teacherAssignments.filter(x=>x.classId===classId&&x.status==='ACTIVE').map(x=>x.teacherId);return res.json({success:true,classGroup:cls,students:studentIds.map(x=>db.findUserById(x)).filter(Boolean).map(u=>({id:u!.id,name:u!.full_name,email:u!.email})),teachers:teacherIds.map(x=>db.findUserById(x)).filter(Boolean).map(u=>({id:u!.id,name:u!.full_name,email:u!.email}))});}
function parseCsv(input:string){const lines=input.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return [];const headers=lines[0].split(',').map(x=>x.trim());return lines.slice(1).map(line=>{const cells=line.split(',').map(x=>x.trim());return Object.fromEntries(headers.map((h,i)=>[h,cells[i]||'']));});}
export function handleBulkImport(req:AuthenticatedRequest,res:Response){const c=ok(req,'students','create');if(!c.allowed)return res.status(403).json({success:false,error:c.reason});const p=z.object({csv:z.string().min(1),mode:z.enum(['PREVIEW','APPLY']).default('PREVIEW')}).safeParse(req.body);if(!p.success)return res.status(400).json({success:false,error:'INVALID_IMPORT'});const rows=parseCsv(p.data.csv);const preview=rows.map((r,i)=>{const role=(r.role||'STUDENT').toUpperCase();const validRole=['STUDENT','TEACHER','ASSISTANT_TEACHER','GUARDIAN'].includes(role);const email=(r.email||'').toLowerCase();const duplicate=db.users.some(u=>u.email.toLowerCase()===email);return {row:i+2,email,role,valid:!!email&&validRole&&!duplicate,errors:[!email?'EMAIL_REQUIRED':'',!validRole?'INVALID_ROLE':'',duplicate?'EMAIL_EXISTS':''].filter(Boolean)};});if(p.data.mode==='PREVIEW')return res.json({success:true,mode:'PREVIEW',total:rows.length,preview});const created=[];for(const item of preview){if(!item.valid)continue;const r=rows[item.row-2];const role=r.role.toUpperCase();const u=db.createUser({email:r.email,passwordHash:hashPasswordSync(r.password||'Password123!'),firstName:r.firstName||r.first_name||'',lastName:r.lastName||r.last_name||'',role:role as any});created.push({id:u.id,email:u.email,role});}persist();return res.status(201).json({success:true,mode:'APPLY',createdCount:created.length,created});}
export const teacherStudentState=state;
