import React, { useEffect, useState } from 'react';

export const PlatformCommandCenterPage: React.FC = () => {
  const [data,setData] = useState<any>(null); const [error,setError] = useState('');
  useEffect(() => { const token=localStorage.getItem('eb_access_token'); fetch('/api/admin/command-center',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(j=>j.success?setData(j.report):setError(j.error?.message||'تعذر تحميل لوحة القيادة')).catch(()=>setError('تعذر الاتصال بالخادم')); },[]);
  if(error) return <div dir="rtl" className="p-8">{error}</div>;
  if(!data) return <div dir="rtl" className="p-8">جاري تحميل مركز قيادة المنصة...</div>;
  const cards=[['المستخدمون',data.users.total],['الطلاب',data.users.students],['المعلمون',data.users.teachers],['الأسئلة',data.academic.questions],['الدروس',data.academic.lessons],['محاولات الأسئلة',data.academic.attempts],['الجلسات النشطة',data.security.activeSessions],['متوسط الإتقان',data.academic.averageMastery===null?'—':`${data.academic.averageMastery}%`]];
  return <div dir="rtl" className="max-w-7xl mx-auto px-4 py-8 space-y-6"><header><h1 className="text-3xl font-black">مركز قيادة منصة رواد بيزنس</h1><p className="text-sm opacity-70">صورة تشغيلية موحدة للمستخدمين والمحتوى والجودة والتعلم التكيفي والأمان.</p></header><section className="grid grid-cols-2 md:grid-cols-4 gap-4">{cards.map(([k,v])=><div key={String(k)} className="border p-4 rounded-lg bg-white"><div className="text-xs opacity-60">{k}</div><div className="text-2xl font-bold mt-2">{v}</div></div>)}</section><section className="grid md:grid-cols-3 gap-4"><div className="border p-5 rounded-lg"><h2 className="font-bold">الجودة الأكاديمية</h2><p>اجتياز: {data.quality.pass}</p><p>مراجعة: {data.quality.review}</p><p>محجوب: {data.quality.blocked}</p><p>قابلية التتبع: {data.quality.traceabilityRate}%</p></div><div className="border p-5 rounded-lg"><h2 className="font-bold">التعلم التكيفي</h2><p>استرداد: {data.adaptive.recovery}</p><p>نمو: {data.adaptive.growth}</p><p>إتقان: {data.adaptive.mastery}</p></div><div className="border p-5 rounded-lg"><h2 className="font-bold">تنبيهات</h2>{data.alerts.length?<ul className="list-disc pr-5 space-y-2">{data.alerts.map((x:string)=><li key={x}>{x}</li>)}</ul>:<p>لا توجد تنبيهات تشغيلية.</p>}</div></section><footer className="text-xs opacity-50">آخر تحديث: {new Date(data.generatedAt).toLocaleString('ar-EG')}</footer></div>;
};
