import React, { useEffect, useState } from 'react';

const ROLE_LABELS: Record<string,string> = { SUPER_ADMIN:'مدير النظام الأعلى', PLATFORM_ADMIN:'مدير المنصة', ACADEMIC_ADMIN:'مدير أكاديمي', TEACHER:'معلم', ASSISTANT_TEACHER:'معلم مساعد', CONTENT_MANAGER:'مدير محتوى', QUESTION_BANK_MANAGER:'مدير بنك الأسئلة', EXAM_MANAGER:'مسؤول امتحانات', REVIEWER:'مراجع أكاديمي', SUPPORT_AGENT:'دعم فني', ANALYST:'محلل', STUDENT:'طالب', GUARDIAN:'ولي أمر' };
const STATUS_LABELS: Record<string,string> = { ACTIVE:'نشط', SUSPENDED:'موقوف', LOCKED:'مقفل', INVITED:'مدعو', PENDING_VERIFICATION:'بانتظار التحقق', DEACTIVATED:'معطل', ARCHIVED:'مؤرشف' };

export const UserManagementPage: React.FC = () => {
  const [summary,setSummary]=useState<any>(null); const [items,setItems]=useState<any[]>([]); const [q,setQ]=useState(''); const [role,setRole]=useState(''); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<string[]>([]); const [message,setMessage]=useState('');
  const token=localStorage.getItem('eb_access_token');
  const headers:any={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  const load=async()=>{setLoading(true); try { const [s,u]=await Promise.all([fetch('/api/admin/user-management/summary',{headers}),fetch(`/api/admin/user-management/users?q=${encodeURIComponent(q)}&role=${role}&status=${status}&page=1&pageSize=50`,{headers})]); const sj=await s.json(); const uj=await u.json(); setSummary(sj); setItems(uj.items||[]); } finally {setLoading(false);} };
  useEffect(()=>{load();},[role,status]);
  const bulk=async(action:string)=>{ if(!selected.length)return; const r=await fetch('/api/admin/user-management/users/bulk',{method:'POST',headers,body:JSON.stringify({userIds:selected,action})}); const j=await r.json(); setMessage(j.success?'تم تنفيذ العملية الجماعية.':'تعذر تنفيذ العملية.'); setSelected([]); load(); };
  const assignRole=async(id:string)=>{const next=prompt('أدخل رمز الدور (مثل TEACHER أو STUDENT):'); if(!next)return; const r=await fetch(`/api/admin/user-management/users/${id}/roles`,{method:'POST',headers,body:JSON.stringify({role:next.toUpperCase(),scopeType:'GLOBAL'})}); const j=await r.json(); setMessage(j.success?'تم تعيين الدور.':(j.error?.message||'تعذر تعيين الدور')); load();};
  return <div dir="rtl" style={{padding:24,maxWidth:1400,margin:'0 auto'}}>
    <h1>إدارة المستخدمين المتقدمة</h1><p>إدارة الطلاب والمعلمين والحسابات والصلاحيات والجلسات من مركز واحد.</p>
    {message&&<div style={{padding:10,margin:'10px 0',border:'1px solid #ddd'}}>{message}</div>}
    {summary&&<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,margin:'20px 0'}}>{[['إجمالي المستخدمين',summary.total],['الجلسات النشطة',summary.activeSessions],['الطلاب',summary.byRole?.STUDENT||0],['المعلمون',summary.byRole?.TEACHER||0]].map(([a,b])=><div key={String(a)} style={{padding:16,border:'1px solid #ddd',borderRadius:10}}><strong>{a}</strong><div style={{fontSize:26,marginTop:8}}>{b}</div></div>)}</div>}
    <div style={{display:'flex',gap:8,marginBottom:16}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالاسم أو البريد"/><select value={role} onChange={e=>setRole(e.target.value)}><option value="">كل الأدوار</option>{Object.entries(ROLE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={load}>بحث</button></div>
    {selected.length>0&&<div style={{display:'flex',gap:8,marginBottom:12}}><button onClick={()=>bulk('ACTIVATE')}>تفعيل</button><button onClick={()=>bulk('SUSPEND')}>إيقاف</button><button onClick={()=>bulk('DEACTIVATE')}>تعطيل</button><button onClick={()=>bulk('ARCHIVE')}>أرشفة</button><button onClick={()=>bulk('UNLOCK')}>فتح القفل</button></div>}
    {loading?<p>جارٍ التحميل...</p>:<table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['','المستخدم','الدور','الحالة','تاريخ الإنشاء','إجراءات'].map(x=><th key={x} style={{textAlign:'right',padding:10,borderBottom:'2px solid #ddd'}}>{x}</th>)}</tr></thead><tbody>{items.map(u=><tr key={u.id}><td style={{padding:10}}><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(x=>x!==u.id))}/></td><td style={{padding:10}}><strong>{u.full_name}</strong><div>{u.email}</div></td><td style={{padding:10}}>{(u.roles||[]).map((r:string)=>ROLE_LABELS[r]||r).join('، ')}</td><td style={{padding:10}}>{STATUS_LABELS[u.status]||u.status}</td><td style={{padding:10}}>{new Date(u.created_at).toLocaleDateString('ar-EG')}</td><td style={{padding:10}}><button onClick={()=>assignRole(u.id)}>تعيين دور</button></td></tr>)}</tbody></table>}
  </div>;
};
